### ISSUE TITLE
Glitch in uncoolify button

### ISSUE THREAD

**Issue by Sumit0581** [NJACKWinterOfCode/cool-name-api#14]
The uncoolify button doesn't work properly for following alphabets: 'b', 'n' and 'd'.
![screenshot from 2018-12-19 21-58-54](https://user-images.githubusercontent.com/36412264/50234932-c687fc80-03dc-11e9-8db1-b4de5444f3e8.png)

**Comment by sourabh1031** [comment]
@Sumit0581 are you working on it ?

**Comment by Sumit0581** [comment]
@sourabh1031 Yes, I am working on it.
